trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  NODE_VERSION: "18.x"

stages:
  - stage: Validate
    jobs:
      - job: lint_test_build
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: $(NODE_VERSION)
          - script: npm ci
            displayName: Install
          - script: npm run typecheck
            displayName: Typecheck
          - script: npm run lint
            displayName: Lint
          - script: npm run test
            displayName: Test
          - script: npm run build
            displayName: Build

  - stage: DeployDev
    dependsOn: Validate
    condition: succeeded()
    jobs:
      - deployment: deploy_dev
        environment: dev
        strategy:
          runOnce:
            deploy:
              steps:
                - task: NodeTool@0
                  inputs:
                    versionSpec: $(NODE_VERSION)
                - script: npm ci
                  displayName: Install
                - script: npx sincronia deploy --env dev
                  displayName: Deploy

  - stage: DeployQa
    dependsOn: DeployDev
    condition: succeeded()
    jobs:
      - deployment: deploy_qa
        environment: qa
        strategy:
          runOnce:
            deploy:
              steps:
                - task: NodeTool@0
                  inputs:
                    versionSpec: $(NODE_VERSION)
                - script: npm ci
                  displayName: Install
                - script: npx sincronia deploy --env qa
                  displayName: Deploy

  - stage: DeployProd
    dependsOn: DeployQa
    condition: succeeded()
    jobs:
      - deployment: deploy_prod
        environment: prod
        strategy:
          runOnce:
            deploy:
              steps:
                - task: NodeTool@0
                  inputs:
                    versionSpec: $(NODE_VERSION)
                - script: npm ci
                  displayName: Install
                - script: npx sincronia deploy --env prod
                  displayName: Deploy
