trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Install
    jobs:
      - job: install
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "18.x"
          - script: npm ci
            displayName: npm ci

  - stage: Lint
    dependsOn: Install
    jobs:
      - job: lint
        steps:
          - script: npm run lint
            displayName: lint

  - stage: Test
    dependsOn: Lint
    jobs:
      - job: test
        steps:
          - script: npm run test
            displayName: test

  - stage: Build
    dependsOn: Test
    jobs:
      - job: build
        steps:
          - script: npm run build
            displayName: build

  - stage: Deploy
    dependsOn: Build
    jobs:
      - deployment: deploy_dev
        environment: dev
        strategy:
          runOnce:
            deploy:
              steps:
                - script: npx sincronia deploy --env dev
                  displayName: deploy
