trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Validate
    jobs:
      - job: verify
        steps:
          - checkout: self
          - task: NodeTool@0
            inputs:
              versionSpec: "18.x"
          - script: npm ci
            displayName: npm ci
          - script: npm run typecheck
            displayName: typecheck
          - script: npm run lint
            displayName: lint
          - script: npm run test
            displayName: test
          - script: npm run build
            displayName: build

  - stage: DeployDev
    dependsOn: Validate
    jobs:
      - deployment: deploy_dev
        environment: dev
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: NodeTool@0
                  inputs:
                    versionSpec: "18.x"
                - script: npm ci
                  displayName: install
                - script: npx sincronia deploy --env dev
                  displayName: deploy dev

  - stage: DeployQa
    dependsOn: DeployDev
    jobs:
      - deployment: deploy_qa
        environment: qa
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: NodeTool@0
                  inputs:
                    versionSpec: "18.x"
                - script: npm ci
                  displayName: install
                - script: npx sincronia deploy --env qa
                  displayName: deploy qa

  - stage: DeployProd
    dependsOn: DeployQa
    jobs:
      - deployment: deploy_prod
        environment: prod
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: NodeTool@0
                  inputs:
                    versionSpec: "18.x"
                - script: npm ci
                  displayName: install
                - script: npx sincronia deploy --env prod
                  displayName: deploy prod
